### ISSUE TITLE
Font-face URL paths are messed up by SASS compiler 

### ISSUE THREAD

**Issue by ETVO** [twbs/icons#1018]
When importing bootstrap-icons.css from the bootstrap-icons npm package, the SASS compiler messes up the way the font-faces are imported. Take a look:

In the original bootstrap-icons.css
```css
@font-face {
  font-family: "bootstrap-icons";
  src: url("./fonts/bootstrap-icons.woff2?856008caa5eb66df68595e734e59580d") format("woff2"),
url("./fonts/bootstrap-icons.woff?856008caa5eb66df68595e734e59580d") format("woff");
}
```

This works beautifully, using the dot in the beggining of the URL path to indicate it is a relative path, so that CSS is able to find the files inside of the "fonts" folder.

Well, I import this file to my `main.scss` file, using: 
```css
@import "~bootstrap-icons/font/bootstrap-icons";
```

Then, I ask webpack to build this SASS and generate a CSS file. Which it does, almost perfectly, even fetching all of the dependencies (like the files imported in the `@font-face` declaration you saw above).

Now, in my "assets" folder, where I ask Webpack to put my CSS files, the directory looks a bit like this:
```
assets/
  css/
    main.css
    fonts/
        bootstrap-icons.woff
        bootstrap-icons.woff2
```

It is fantastic! Until it is not. In the CSS file, the import declaration looks like the following:
```css
@font-face {
  font-family: "bootstrap-icons";
  src: url(/fonts/vendor/bootstrap-icons/bootstrap-icons.woff2?dfd0ea122577eb61795f178e0347fa2c) format("woff2"),
url(/fonts/vendor/bootstrap-icons/bootstrap-icons.woff?94eeade15e6b7fbed95b18ff32f0c112) format("woff");
}
```
**It is almost exactly the same as in the original file, but now the dots in the beginning of the paths were removed, so CSS can't find the font files.** It keeps giving me the 404 (Not Found) error, and the icons are not shown.

The solution to my problem is very simple: copying the original bootstrap-icons module files to my project, but of course it is not as convenient nor can it be minified (without messing up the dots in the URLs).

I would like to know if anyone has had this problem, and if there's a way for us to actually make this work.

Thanks!
