### ISSUE TITLE
Square Framed icon sizing differences

### ISSUE THREAD

**Issue by scottdorman** [twbs/icons#1918]
The "square framed" icons, like `bi-x-square` and `bi-pencil-square` are not all the same size. When displayed separately, it's not noticeable, but when shown next to each other, the size difference is just enough to create an inconsistent feel. I've attached a screenshot of the two icons next to each other that shows the slight size difference.

![image](https://github.com/twbs/icons/assets/2532850/9f1efe5c-0041-4837-9f23-9f8aa7657bfb)

The relevant HTML is
```html
<td data-shepherd-id="row-actions">
   <i class="bi bi-x-square fs-3 action-button" data-action-type="remove-row" title="Remove row"></i>
   <i class="bi bi-pencil-square fs-3 action-button" title="Edit row"></i>
</td>
```

The CSS being applied is
```css
.action-button:hover {
    color: var(--theme-color-link-hover);
    cursor: pointer;
}

.action-button[data-action-type='remove-row']:hover {
    color: var(--bs-danger);
}
```

I've only tested this in Microsoft Edge.
