### ISSUE TITLE
Add hover icons

### ISSUE THREAD

**Issue by Styrak** [twbs/icons#2162]
To improve the user experience, we've built a CSS extension using your existing styles, with the sole purpose of changing the icon on hover.
Maybe you can implement it.

```css
.bi-123-hover:hover::before { content: "\f67f"; }
.bi-alarm-fill-hover:hover::before { content: "\f101"; }
.bi-alarm-hover:hover::before { content: "\f102"; }
.bi-align-bottom-hover:hover::before { content: "\f103"; }
.bi-align-center-hover:hover::before { content: "\f104"; }
.bi-align-end-hover:hover::before { content: "\f105"; }
```
