### ISSUE TITLE
Icon vertical alignment and size issues

### ISSUE THREAD

**Issue by tmorehouse** [twbs/icons#82]
It appears that the icons, when paced inside dropdowns and butons, is slightly off vertically (baseline is not quite lined up with the font), as well as when icons are placed inline with text.

A fix we have implemented is as follows:

```scss
.bi {
  vertical-align: -0.125em;
  margin-bottom: calc(-0.125em / 2);
}

// Make icons slightly larger (aesthetically) in input group prepend/append
.input-group {
  .input-group-text {
    .bi {
      transform: scale(1.5);
    }
  }
}

// Make icons slightly larger (aesthetically) in buttons and dropdowns
.btn,
.dropdown {
   .bi {
    transform: scale(1.5);
    // reset the bottom margin from above
    margin-bottom: 0;
  }
}
```

### Before

![image](https://user-images.githubusercontent.com/2781561/70848194-32f8d880-1e44-11ea-88a6-2bb8c664a9b4.png)

![image](https://user-images.githubusercontent.com/2781561/70848217-7ce1be80-1e44-11ea-8ce1-7681f5e0e226.png)

![image](https://user-images.githubusercontent.com/2781561/70848236-a7cc1280-1e44-11ea-816f-b38bc1dec5af.png)

![image](https://user-images.githubusercontent.com/2781561/70848248-d5b15700-1e44-11ea-8221-c7f3197cb8e7.png)

### After

![image](https://user-images.githubusercontent.com/2781561/70848199-4efc7a00-1e44-11ea-83f4-6c1223fca6ad.png)

![image](https://user-images.githubusercontent.com/2781561/70848226-91be5200-1e44-11ea-96da-606af9476359.png)

![image](https://user-images.githubusercontent.com/2781561/70848239-b9adb580-1e44-11ea-875c-84ad1bb8bde6.png)

![image](https://user-images.githubusercontent.com/2781561/70848254-ebbf1780-1e44-11ea-8423-a701251205cd.png)
