### ISSUE TITLE
Webpack can't process the garbled font-face path in the NPM package

### ISSUE THREAD

**Issue by TropicalRaisel** [twbs/icons#944]
```
Error: Can't resolve './fonts/bootstrap-icons.woff2?856008caa5eb66df68595e734e59580d' in ...
```

Currently looks like:
```css
@font-face {
  font-family: "bootstrap-icons";
  src: url("./fonts/bootstrap-icons.woff2?856008caa5eb66df68595e734e59580d") format("woff2"),
url("./fonts/bootstrap-icons.woff?856008caa5eb66df68595e734e59580d") format("woff");
}
```
Should be like:
```css
@font-face {
  font-family: "bootstrap-icons";
  src: url("./fonts/bootstrap-icons.woff2") format("woff2"),
url("./fonts/bootstrap-icons.woff") format("woff");
}
```
